-- Isa Rossi: execute em um projeto Supabase exclusivo antes de ativar a agenda.
create extension if not exists btree_gist;
create table if not exists public.isa_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.isa_services (
  id bigint generated by default as identity primary key,
  name text not null unique,
  duration_minutes int not null check (duration_minutes between 15 and 240 and duration_minutes % 15 = 0),
  price numeric(10,2) check (price >= 0),
  active boolean not null default true
);
create table if not exists public.isa_working_hours (
  weekday int primary key check(weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  active boolean not null default true,
  check(end_time > start_time)
);
create table if not exists public.isa_appointments (
  id uuid primary key default gen_random_uuid(),
  service_id bigint not null references public.isa_services(id),
  customer_name text not null check(length(customer_name) between 2 and 120),
  phone text not null check(length(phone) between 8 and 25),
  email text,
  notes text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'pending' check(status in ('pending','confirmed','completed','cancelled','no_show')),
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);
-- PostgreSQL garante que dois atendimentos ativos nunca se sobreponham.
alter table public.isa_appointments drop constraint if exists isa_no_overlap;
alter table public.isa_appointments add constraint isa_no_overlap exclude using gist
(tstzrange(starts_at,ends_at,'[)') with &&)
where (status in ('pending','confirmed','completed'));
insert into public.isa_services(name,duration_minutes,price)
values ('Drenagem linfática — atendimento',60,null)
on conflict (name) do nothing;
insert into public.isa_working_hours(weekday,start_time,end_time,active)
values (0,'09:00','18:00',false),(1,'09:00','18:00',true),(2,'09:00','18:00',true),
(3,'09:00','18:00',true),(4,'09:00','18:00',true),(5,'09:00','18:00',true),(6,'09:00','13:00',false)
on conflict (weekday) do nothing;
alter table public.isa_admins enable row level security;
alter table public.isa_services enable row level security;
alter table public.isa_working_hours enable row level security;
alter table public.isa_appointments enable row level security;
revoke all on public.isa_admins,public.isa_services,public.isa_working_hours,public.isa_appointments from anon,authenticated;
grant select on public.isa_services to anon,authenticated;
grant select on public.isa_working_hours to authenticated;
grant select,insert,update,delete on public.isa_services,public.isa_working_hours,public.isa_appointments to authenticated;
grant select on public.isa_admins to authenticated;
grant usage, select on all sequences in schema public to authenticated;
create or replace function public.is_isa_admin() returns boolean language sql stable security definer
set search_path = '' as $$ select exists(select 1 from public.isa_admins a where a.user_id = (select auth.uid())); $$;
revoke all on function public.is_isa_admin() from public,anon;
grant execute on function public.is_isa_admin() to authenticated;
drop policy if exists isa_services_public on public.isa_services;
create policy isa_services_public on public.isa_services for select to anon,authenticated using (active);
drop policy if exists isa_services_admin_read on public.isa_services;
create policy isa_services_admin_read on public.isa_services for select to authenticated using(public.is_isa_admin());
drop policy if exists isa_services_admin on public.isa_services;
create policy isa_services_admin on public.isa_services for all to authenticated using(public.is_isa_admin()) with check(public.is_isa_admin());
drop policy if exists isa_hours_admin on public.isa_working_hours;
create policy isa_hours_admin on public.isa_working_hours for all to authenticated using(public.is_isa_admin()) with check(public.is_isa_admin());
drop policy if exists isa_appointments_admin on public.isa_appointments;
create policy isa_appointments_admin on public.isa_appointments for all to authenticated using(public.is_isa_admin()) with check(public.is_isa_admin());
drop policy if exists isa_admins_self on public.isa_admins;
create policy isa_admins_self on public.isa_admins for select to authenticated using(user_id=auth.uid());
-- RPC retorna apenas horários, nunca nome, telefone ou qualquer dado das clientes.
create or replace function public.isa_available_slots(p_service_id bigint,p_date date)
returns table(slot_time text) language plpgsql security definer set search_path='' as $$
declare svc public.isa_services%rowtype; hrs public.isa_working_hours%rowtype; t time; a timestamptz; b timestamptz;
begin
  if p_date < (now() at time zone 'America/Sao_Paulo')::date or p_date > (now() at time zone 'America/Sao_Paulo')::date + 90 then return; end if;
  select * into svc from public.isa_services where id=p_service_id and active;
  if not found then return; end if;
  select * into hrs from public.isa_working_hours where weekday=extract(dow from p_date)::int and active;
  if not found then return; end if;
  t:=hrs.start_time;
  while t + make_interval(mins=>svc.duration_minutes) <= hrs.end_time loop
    a:=(p_date::text || ' ' || t::text)::timestamp at time zone 'America/Sao_Paulo';
    b:=a+make_interval(mins=>svc.duration_minutes);
    if a>now() and not exists(select 1 from public.isa_appointments x where x.status in ('pending','confirmed','completed') and tstzrange(x.starts_at,x.ends_at,'[)') && tstzrange(a,b,'[)')) then
      slot_time:=to_char(t,'HH24:MI'); return next;
    end if;
    t:=t+interval '30 minutes';
  end loop;
end $$;
revoke all on function public.isa_available_slots(bigint,date) from public;
grant execute on function public.isa_available_slots(bigint,date) to anon,authenticated;
-- Reservas são criadas por RPC, com horário validado no banco.
create or replace function public.isa_book(p_service_id bigint,p_date date,p_time text,p_name text,p_phone text,p_email text default null,p_notes text default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare s public.isa_services%rowtype; start_at timestamptz; appointment_id uuid;
begin
 if length(trim(p_name)) not between 2 and 120 or length(trim(p_phone)) not between 8 and 25 or length(coalesce(p_notes,''))>1000
 then raise exception 'Dados inválidos'; end if;
 if not exists(select 1 from public.isa_available_slots(p_service_id,p_date) v where v.slot_time=p_time) then raise exception 'Horário indisponível'; end if;
 select * into s from public.isa_services where id=p_service_id and active;
 start_at:=(p_date::text || ' ' || p_time)::timestamp at time zone 'America/Sao_Paulo';
 insert into public.isa_appointments(service_id,customer_name,phone,email,notes,starts_at,ends_at)
 values(p_service_id,trim(p_name),trim(p_phone),nullif(trim(coalesce(p_email,'')),''),nullif(trim(coalesce(p_notes,'')),''),start_at,start_at+make_interval(mins=>s.duration_minutes))
 returning id into appointment_id;
 return appointment_id;
exception when exclusion_violation then raise exception 'Esse horário acabou de ser reservado';
end $$;
revoke all on function public.isa_book(bigint,date,text,text,text,text,text) from public;
grant execute on function public.isa_book(bigint,date,text,text,text,text,text) to anon,authenticated;
-- Após cadastrar e confirmar o e-mail da administradora no Auth, execute:
-- insert into public.isa_admins(user_id) values ('UUID-DO-USUARIO-ADMIN');
-- Não habilite cadastro público de usuários no Auth, pois clientes não precisam de login.
